/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package portalbruxa.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import portalbruxa.model.BancoFake;

/**
 *
 * @author Lucas
 */
public class Navbar extends javax.swing.JPanel {

    /**
     * Creates new form Navbar
     */
    public Navbar() {
        this.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 10)); 
        initComponents();
        setPreferredSize(new Dimension(Short.MAX_VALUE, 30)); 
        pSubmenu.setVisible(false);
        // Redimensionar o ícone
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/logo_portal_bruxa.png"));
        Image img = originalIcon.getImage();
        Image resizedImg = img.getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon = new ImageIcon(resizedImg);
        jLabel8.setIcon(resizedIcon);
        jLabel8.setText("");
        jLabel8.setPreferredSize(new Dimension(60, 60));
        
        // Controle dos botões baseados no usuário logado
        if (BancoFake.usuarioLogado != null && BancoFake.usuarioLogado.isAdmin()) {
            // Mostra o botão Criar
            btCriar.setVisible(true);
        } else {
            // Oculta o botão Criar para usuários comuns
            btCriar.setVisible(false);
            btVisualizar.setVisible(false);
            pSubmenu.setVisible(false); 
            btArtigos.setForeground(new Color(204,51,255));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btArtigos = new javax.swing.JButton();
        pSubmenu = new javax.swing.JPanel();
        btVisualizar = new javax.swing.JButton();
        btCriar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btLogout = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setPreferredSize(new java.awt.Dimension(1000, 50));

        jLabel8.setText("jLabel8");
        add(jLabel8);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(204, 51, 255));
        jLabel2.setText("Home");
        add(jLabel2);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(204, 51, 255));
        jLabel3.setText("Magia");
        add(jLabel3);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(204, 51, 255));
        jLabel4.setText("Numerologia");
        add(jLabel4);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(204, 51, 255));
        jLabel5.setText("Tarot");
        add(jLabel5);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(204, 51, 255));
        jLabel6.setText("Astrologia");
        add(jLabel6);

        btArtigos.setForeground(new java.awt.Color(153, 0, 204));
        btArtigos.setText("Artigos ");
        btArtigos.setBorder(null);
        btArtigos.setBorderPainted(false);
        btArtigos.setContentAreaFilled(false);
        btArtigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArtigosActionPerformed(evt);
            }
        });
        add(btArtigos);

        pSubmenu.setBackground(new java.awt.Color(255, 255, 255));
        pSubmenu.setPreferredSize(new java.awt.Dimension(100, 78));

        btVisualizar.setForeground(new java.awt.Color(153, 0, 204));
        btVisualizar.setText("Visualizar");
        btVisualizar.setBorder(null);
        btVisualizar.setBorderPainted(false);
        btVisualizar.setContentAreaFilled(false);
        btVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarActionPerformed(evt);
            }
        });

        btCriar.setForeground(new java.awt.Color(153, 0, 204));
        btCriar.setText("Criar");
        btCriar.setBorder(null);
        btCriar.setBorderPainted(false);
        btCriar.setContentAreaFilled(false);
        btCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSubmenuLayout = new javax.swing.GroupLayout(pSubmenu);
        pSubmenu.setLayout(pSubmenuLayout);
        pSubmenuLayout.setHorizontalGroup(
            pSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSubmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        pSubmenuLayout.setVerticalGroup(
            pSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSubmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btVisualizar)
                .addGap(18, 18, 18)
                .addComponent(btCriar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(pSubmenu);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(204, 51, 255));
        jLabel7.setText("Cursos");
        add(jLabel7);

        btLogout.setForeground(new java.awt.Color(153, 0, 204));
        btLogout.setText("Logout");
        btLogout.setBorder(null);
        btLogout.setBorderPainted(false);
        btLogout.setContentAreaFilled(false);
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });
        add(btLogout);
    }// </editor-fold>//GEN-END:initComponents

    private void btArtigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArtigosActionPerformed
        // TODO add your handling code here:
        if (BancoFake.usuarioLogado != null && BancoFake.usuarioLogado.isAdmin()) {
            // Mostra o submenu
            pSubmenu.setVisible(!pSubmenu.isVisible());
        } else {
            // Oculta o submenu
            pSubmenu.setVisible(false);
        }
    }//GEN-LAST:event_btArtigosActionPerformed

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarActionPerformed
        // TODO add your handling code here:
        TelaVisualizarArtigo telaVisualizar = new TelaVisualizarArtigo();
        telaVisualizar.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btVisualizarActionPerformed

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed
        // TODO add your handling code here:
        TelaCadastrarArtigo telaCriar = new TelaCadastrarArtigo();
        telaCriar.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btArtigos;
    private javax.swing.JButton btCriar;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pSubmenu;
    // End of variables declaration//GEN-END:variables
}
