/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package portalbruxa.view;

import portalbruxa.model.Artigo;
import portalbruxa.model.BancoFake;

/**
 *
 * @author Lucas
 */
public class TelaVisualizarArtigo extends javax.swing.JFrame {

    /**
     * Creates new form TelaVisualizarArtigo
     */
    public TelaVisualizarArtigo() {
        initComponents();
        pArtigos.setLayout(new javax.swing.BoxLayout(pArtigos, javax.swing.BoxLayout.Y_AXIS));
        carregarArtigos();
    }

    private void carregarArtigos() {

        for (Artigo artigo : BancoFake.artigos) {
            Card card = new Card();

            card.setTitulo(artigo.getTitulo());
            card.setDescricao(artigo.getConteudo());

            pArtigos.add(card);
        }

        pArtigos.revalidate();
        pArtigos.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar1 = new portalbruxa.view.Navbar();
        pArtigos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navbar1.setBackground(new java.awt.Color(255, 255, 255));
        navbar1.setPreferredSize(new java.awt.Dimension(900, 90));
        getContentPane().add(navbar1, java.awt.BorderLayout.PAGE_START);

        pArtigos.setBackground(new java.awt.Color(102, 0, 102));
        pArtigos.setPreferredSize(new java.awt.Dimension(1000, 800));

        javax.swing.GroupLayout pArtigosLayout = new javax.swing.GroupLayout(pArtigos);
        pArtigos.setLayout(pArtigosLayout);
        pArtigosLayout.setHorizontalGroup(
            pArtigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        pArtigosLayout.setVerticalGroup(
            pArtigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        getContentPane().add(pArtigos, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVisualizarArtigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private portalbruxa.view.Navbar navbar1;
    private javax.swing.JPanel pArtigos;
    // End of variables declaration//GEN-END:variables
}
